### ISSUE TITLE
Command: JOIN

### ISSUE THREAD

**Issue by Elena-Lou** [Elena-Lou/ft_irc#6]
Parameters: \<channel\>{,<channel>} [\<key\>{,\<key\>}]

Used by client to start listening a specific channel. Whether or not a client is allowed to join a channel is checked only by the server the client is connected to; all other servers automatically add the user to the channel when it is received from other servers.  The conditions which affect this are as follows:

           1.  the user must be invited if the channel is invite-only;
           2.  the user's nick/username/hostname must not match any active bans;
           3.  the correct key (password) must be given if it is set.

Once a user has joined a channel, they receive notice about all commands their server receives which affect the channel.  This includes MODE, KICK, PART, QUIT and of course PRIVMSG/NOTICE.  The JOIN command needs to be broadcast to all servers so that each server knows where to find the users who are on the channel.  This allows optimal delivery of PRIVMSG/NOTICE messages to the channel.
If a JOIN is successful, the user receives a JOIN message as confirmation and is then sent the channel's topic (using RPL_TOPIC) and the list of users who are on the channel (using RPL_NAMREPLY), which MUST include the user joining.

Examples:

   JOIN #foobar                               _; join channel #foobar._

   JOIN &foo fubar                          _; join channel &foo using key "fubar"._

   JOIN #foo,&bar fubar                 _; join channel #foo using key "fubar" and &bar using no key._

   JOIN #foo,#bar fubar,foobar     _; join channel #foo using key "fubar" and channel #bar using key "foobar"._

   JOIN #foo,#bar                             _; join channels #foo and #bar._

  :WiZ JOIN #Twilight_zone           _; JOIN message from WiZ_

ERROR replies:
- **ERR_NEEDMOREPARAMS** - 461
"<command> :Not enough parameters"
                -> Returned by the server by numerous commands to indicate to the client that it didn't supply enough parameters.

- **ERR_BANNEDFROMCHAN** - 474
"\<channel\> :Cannot join channel (+b)"
- **ERR_INVITEONLYCHAN** - 473
"\<channel\> :Cannot join channel (+i)"
- **ERR_BADCHANNELKEY** - 475
"\<channel\> :Cannot join channel (+k)"
- **ERR_CHANNELISFULL** - 471
"\<channel\> :Cannot join channel (+l)"
- **ERR_BADCHANMASK** - 476
"\<channel\> :Bad Channel Mask"
                 => Any command requiring operator privileges to operate must return this error to indicate the attempt was unsuccessful

- **ERR_NOSUCHCHANNEL** - 403
"\<channel name\> :No such channel"
                -> Used to indicate the given channel name is invalid.

- **ERR_TOOMANYCHANNELS** - 405
"\<channel name\> :You have joined too many channels"
                -> Sent to a user when they have joined the maximum number of allowed channels and they try to join another channel.

Command response:
- **RPL_TOPIC** - 332
"\<channel\> :\<topic\>"
                -> When sending a TOPIC message to determine the channel topic, one of two replies is sent.  If the topic is set, RPL_TOPIC is sent back else RPL_NOTOPIC.

**Comment by AdrianWeaver** [comment]
From the rfc1459:

Channels names are strings (beginning with a '&' or '#' character) of length up to 200 characters.  Apart from the the requirement that the first character being either '&' or '#'; the only restriction on a channel name is that it may not contain any spaces (' '), a control G (^G or ASCII 7), or a comma (',' which is used as a list item separator by the protocol).

**Comment by AdrianWeaver** [comment]
Started working on JOIN in branch aw/commands.
Putting this back in "TODO" at the benefice of command NICK that seems more important.
