### ISSUE TITLE
Command: USER

### ISSUE THREAD

**Issue by Elena-Lou** [Elena-Lou/ft_irc#7]
Parameters: \<user\> \<mode\> \<unused\> \<realname\>

Used at the beginning of connection to specify the username, hostname and realname of a new user.

The <mode> parameter should be a numeric, and can be used to automatically set user modes when registering with the server.  This parameter is a bitmask, with only 2 bits having any signification: if the bit 2 is set, the user mode 'w' will be set and if the bit 3 is set, the user mode 'i' will be set.

The \<realname\> may contain space characters.

Examples:

USER guest 0 * :Ronnie Reagan   _; User registering themselves with a  username of "guest" and real name "Ronnie Reagan"._

USER guest 8 * :Ronnie Reagan   _; User registering themselves with a username of "guest" and real name "Ronnie Reagan", and asking to be set invisible._

ERROR replies:

- **ERR_NEEDMOREPARAMS** - 461
"\<command\> :Not enough parameters"
         -> Returned by the server by numerous commands to indicate to the client that it didn't supply enough parameters.

- **ERR_ALREADYREGISTRED** - 462
":Unauthorized command (already registered)"
         -> Returned by the server to any link which tries to change part of the registered details (such as password or user details from second USER message).

**Comment by AdrianWeaver** [comment]
The USER command is somewhat linked to two other commands "PASS" and "NICK".
The three commands constitute the complete "registration".

They must be given in this order 
- PASS
- USER
- NICK

A user that did not complete the registration is not allowed to use other commands (at least in the scope of the project, see CAP and SASL for details)

if the server is password protected, it shall check that the user gave the correct password phrase.
The user can send several passphrase only the last one given will be compared. Then once the registration is complete the user cannot change it's registered password (hence the error 462 - ERR_ALREADYREGISTERED)

This leads to addition in our current structure :
Server:
- bool _isPasswordProtected;
- string _password;

Client:
- bool registered (needs to be checked for all the commands).
- string _passPhrase;

Moreover if Client._username or Client._nickname is set, PASS is not allowed.
Also if Client._username is not set, NICK is not allowed. (This will never happen using IRSSI, but still we could add a check).
